# Generated by Django 4.0 on 2021-12-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_coordinator',
            new_name='is_coordinator',
        ),
    ]
